version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - config/.env
      - apps/backend/.env
    volumes:
      - ./apps/backend:/apps/backend
    networks:
      - smartpyme-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - config/.env
      - apps/frontend/.env
    volumes:
      - ./apps/frontend:/apps/frontend
      - frontend-next:/apps/frontend/.next
    depends_on:
      - backend
    networks:
      - smartpyme-network

networks:
  smartpyme-network:
    driver: bridge

volumes:
  frontend-next:
